version: '3.5'
services:
  postgres:
    container_name: postgres
    image: postgres
    hostname: postgres
    command: postgres -c listen_addresses='*'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: users_api
      POSTGRES_DB: users_db
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    networks:
      - local
    restart: unless-stopped

networks:
  local:
    driver: bridge
